name: 'PaLM log analysis Action'
description: 'Generate summaries of logs as artifacts'

inputs:
  api-key:
    description: 'PaLM API key'
    required: true
  file:
    description: 'Path of file to summarize'
    required: true

outputs:
  summary:
    description: "Summary of the logs"

runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.file }}
    - ${{ inputs.api-key }}
