on:
  push

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Test
        uses: ./
        id: ok
        with:
          api-key: 12
          filename: test.py

      - name: opt
        run: echo "${{ steps.ok.outputs.summary }}"
